# Generated by Django 5.1.1 on 2024-10-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querer', models.BooleanField()),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_sangue', models.CharField(max_length=10)),
                ('fuma', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('doenca', models.CharField(max_length=10)),
                ('doenca_det', models.CharField(max_length=10)),
                ('disponibilidade', models.CharField(max_length=10)),
                ('dias', models.CharField(max_length=10)),
            ],
        ),
    ]
