# Generated by Django 5.1.2 on 2024-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_campanhas_alter_questionario_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhas',
            name='titulo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
