# Generated by Django 5.1.2 on 2024-10-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_campanhas_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanhas',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='campanhas',
            name='image',
        ),
    ]
