# Generated by Django 5.1.2 on 2024-10-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_campanhas_descricao_remove_campanhas_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhas',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campanhas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='titulo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
