# Generated by Django 5.1.2 on 2024-11-12 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_questionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
