# Generated by Django 5.1.2 on 2024-11-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_questionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
