# Generated by Django 5.1.2 on 2024-11-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='idade',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
