# Generated by Django 5.1.2 on 2024-11-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_questionario_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='idade',
            field=models.IntegerField(null=True),
        ),
    ]
