# Generated by Django 5.1.2 on 2024-11-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_questionario_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.DateTimeField()),
                ('data_prox_doacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='questionario',
            name='tipo_sangue',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Não sabe', 'Não sabe')], default=True, max_length=10),
        ),
    ]
