# Generated by Django 5.1.2 on 2024-11-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_doacoes_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacoes',
            name='usuario',
        ),
    ]
