# Generated by Django 5.1.2 on 2024-11-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_remove_doacoes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacoes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
