# Generated by Django 5.1.2 on 2024-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_doacoes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_criadores/')),
                ('nome', models.TextField(max_length=180)),
                ('instagram', models.TextField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('descricao', models.TextField(max_length=300)),
            ],
        ),
    ]
