# Generated by Django 5.1.2 on 2024-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criador',
            name='descricao',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='criador',
            name='nome',
            field=models.TextField(max_length=50),
        ),
    ]
