# Generated by Django 5.1.2 on 2024-11-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_criador_descricao_alter_criador_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criador',
            name='instagram',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='criador',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
