# Generated by Django 5.1.2 on 2024-11-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_criador_instagram_alter_criador_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255, unique=True, verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
            ],
        ),
    ]
