# Generated by Django 5.1.2 on 2024-11-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_chatfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfaq',
            name='pergunta',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chatfaq',
            name='resposta',
            field=models.TextField(),
        ),
    ]
