# Generated by Django 5.1.2 on 2024-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_chatfaq_pergunta_alter_chatfaq_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhas',
            name='data_campanha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
