# Generated by Django 5.1.2 on 2024-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_campanhas_data_campanha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhas',
            name='data_campanha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
