# Generated by Django 5.1.2 on 2024-12-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_campanhas_data_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
