# Generated by Django 5.1.2 on 2024-12-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_questionario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfaq',
            name='foto_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
