# Generated by Django 5.1.2 on 2024-12-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_chatfaq_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatfaq',
            name='foto_perfil',
        ),
    ]
